[book]
title = "通过例子学 Rust"
description = "通过例子学 Rust, Rust By Example 中文版，RBE 中文版"
author = "The Rust Community"
language = "zh"

[output.html]
theme = "theme"
git-repository-url = "https://github.com/budshome/rust-by-example-zh"

[output.html.playpen]
editable = true
editor = "ace"
